# 1章：ニューラルネットワークの復習

## 1.1 数学とPythonの復習

### 1.1.1 ベクトルと行列

In [2]:
import numpy as np
x = np.array([1, 2, 3])
x.__class__

numpy.ndarray

In [9]:
x

array([1, 2, 3])

In [5]:
x.shape # 多次元配列の形状を表示

(3,)

In [4]:
x.ndim # 次元数を表示

1

In [7]:
W = np.array([[1,2,3], [4,5,6]])

In [10]:
W

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
W.shape

(2, 3)

In [12]:
W.ndim # 次元数を表示

2

### 1.1.2 行列の要素ごとの演算

In [15]:
W = np.array([[1,2,3], [4,5,6]])

In [16]:
X = np.array([[0,1,2], [3,4,5]])

In [17]:
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [19]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

### 1.1.3 ブロードキャスト

In [20]:
A = np.array([[1, 2], [3,4]])

In [21]:
A * 10

array([[10, 20],
       [30, 40]])

In [22]:
A = np.array([[1, 2], [3,4]])

In [23]:
b = np.array([10, 20])

In [24]:
A * b

array([[10, 40],
       [30, 80]])

### 1.1.4 ベクトルの内積と行列の積

In [25]:
#  ベクトルの内積
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [27]:
# 行列の積
A = np.array([[1, 2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [29]:
B = np.array([[5, 6], [7,8]])
B

array([[5, 6],
       [7, 8]])

In [30]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])