# 1章：ニューラルネットワークの復習

## 1.2 ニューラルネットワークの推論

### 1.2.1 ニューラルネットワークの推論の全体図

In [1]:
import numpy as np
W1 = np.random.randn(2, 4) # 重み
b1 = np.random.randn(4) # バイアス
x = np.random.randn(10, 2) # 入力
h = np.dot(x, W1) + b1
h # hは 10 x 4 の形状

array([[-0.93066443, -1.13614467,  0.83929439,  1.0575558 ],
       [-2.54532404,  0.5026538 ,  2.2467783 , -0.08449728],
       [-0.69527447,  0.04342654,  1.88736827,  4.06247293],
       [-5.58057192,  2.55327561,  3.98254417, -4.2924048 ],
       [-1.47446046, -1.39161191,  0.59996546, -0.94269216],
       [ 0.30732788, -1.84902099,  0.24045245,  3.02099996],
       [-0.54237674, -2.30808627, -0.18642065, -0.22430863],
       [-2.6977441 ,  0.39817845,  2.150655  , -0.71092016],
       [ 0.41546132, -1.77386532,  0.30956211,  3.46748535],
       [-0.60161428, -1.00919697,  0.95969566,  2.21260399]])

In [2]:
# シグモイド関数
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
a = sigmoid(h)
a

array([[0.28278993, 0.24302891, 0.69831658, 0.74222318],
       [0.07274125, 0.62308278, 0.90437228, 0.47888824],
       [0.33286077, 0.51085493, 0.86845517, 0.98308464],
       [0.00375625, 0.92779327, 0.98170286, 0.0134876 ],
       [0.18626559, 0.19915055, 0.6456484 , 0.28035686],
       [0.57623289, 0.13598789, 0.55982515, 0.95351387],
       [0.36763486, 0.09045547, 0.45352934, 0.44415679],
       [0.0631066 , 0.59824994, 0.89572997, 0.32939555],
       [0.60239668, 0.1450623 , 0.57677837, 0.96974833],
       [0.35397446, 0.26713703, 0.72306087, 0.90137566]])

In [4]:
import numpy as np

# シグモイド関数
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.random.randn(10, 2) # 入力
W1 = np.random.randn(2, 4) # 重み（1層目）
b1 = np.random.randn(4) # バイアス（1層目）
W2 = np.random.randn(4, 3) # 重み（2層目）
b2 = np.random.randn(3) # バイアス（2層目）

h = np.dot(x, W1) + b1
a = sigmoid(h)
s = np.dot(a, W2) + b2
s

array([[ 1.24372905,  0.82877752, -0.93075819],
       [ 1.42270696,  1.47724685, -1.49064625],
       [ 1.79355474,  0.88149722, -1.32965212],
       [ 1.28090614,  1.50678927, -1.52294883],
       [ 1.52706425,  1.0925249 , -1.26555571],
       [ 1.83711864,  1.62364438, -1.85613083],
       [ 1.46922108,  0.50188823, -0.77641643],
       [ 1.13774227,  0.60210355, -0.75730433],
       [ 0.92346046,  1.35816506, -1.42670972],
       [ 1.20951758,  0.98978377, -1.01922827]])

### 1.2.2 レイヤとしてのクラス化と順伝播の実装

In [12]:
# coding: utf-8
import numpy as np

# シグモイド層（Sigmoidレイヤ）
class Sigmoid:
    def __init__(self):
        self.params = []

    def forward(self, x): # 順伝播
        # シグモイド関数
        return 1 / (1 + np.exp(-x))

# 全結合層 （ affineレイヤ）   
class Affine:
    def __init__(self, W, b): # 初期化時に重みとバイアスを受け取る
        self.params = [W, b]

    def forward(self, x): # 順伝播
        W, b = self.params
        out = np.dot(x, W) + b
        return out

    
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 重みとバイアスの初期化
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # レイヤの生成
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # すべての重みをリストにまとめる
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x    
    
x = np.random.randn(10, 2) # xの形状は(10, 2) 2次元のデータが10個 
model = TwoLayerNet(2, 4, 3) # 入力層のニューロンが2、隠れ層のニューロンが4、出力層のニューロンを3個とする
s = model.predict(x)
print(s)    

[[-0.88444325 -0.77918377 -0.10778886]
 [-0.7842112  -0.63181642 -1.46456064]
 [-0.9777251  -0.67257563 -0.93044016]
 [-0.83823337 -0.72982782 -0.77033122]
 [-0.70175492 -0.59711376 -1.6434957 ]
 [-0.97309071 -0.70672583 -0.58329047]
 [-0.83456485 -0.65225296 -1.32210065]
 [-0.60159631 -0.42230648 -2.17174246]
 [-0.55699378 -0.30609167 -2.40600092]
 [-0.98584541 -0.68493283 -0.78080486]]
